### ISSUE TITLE
Поиск всех файлов в директории по паттерну

### ISSUE THREAD

**Issue by PavelICS** [PavelICS/checker21#1]

**Comment by Talpik** [comment]
Скрипт подготовил. 
Основная функция называется: 
`def get_files_with_pattern(project_dir: Path, pattern: str = '*', recursive: bool = True) -> Generator:`
Внутри неё используется дополнительная функция:
`def parse_pattern(pattern: str) -> List[str]:`
В файле зависимостей указан необходимый пакет `wcmatch.pathlib`, так как он позволяет в функции glob или rglob принимать в качестве аргумента список строк и возвращать нужный Генератор. А иначе, при необходимости поиска группы расширений стандартный pathlib.Path.glob примает только str и пришлось бы итеррироваться по списку расширений и компоновать результирующий список найденых файлов. Наверное можно было бы написать свой генератор..

**Comment by PavelICS** [comment]
1) Чтоб дать больше возможностей для чекеров. Например, поиск запрещённых файлов. Проще pattern компилировать в подходящую регулярку.
`*` заменяется на `.*`
`.` заменяется на `\.`
Замены производить, если перед `*` или `.` чётное число символов `\` (0, 2, 4...).
Полученную строку передать в `re.compile`.

2) Функция, которая проверит переданный путь на соответствие скомпилированной регулярке из пункта 1.

3) Отдельно функцию генератор, которая через `iterdirs` пройдётся по всем файлам и директориям.

4) И наша финальная функция для каждого файла из пункта 3 сделает проверку на соответствие нашей регулярке из пункта 1 через функцию из пункта 2.
